name = "enrichment-capital"
compatibility_date = "2025-07-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./out"
# For Next.js static export
binding = "ASSETS"

[[env.production.routes]]
pattern = "enrichmentcapital.pages.dev/*"
zone_name = "pages.dev"
